In [2]:
import torch
from scipy.constants import troy_pound

x = torch.arange(3)
y = torch.arange(3)
x, y

(tensor([0, 1, 2]), tensor([0, 1, 2]))

In [5]:
yv, xv = torch.meshgrid([y, x], indexing='ij')
yv, xv

(tensor([[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2]]),
 tensor([[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]]))

In [9]:
result = torch.stack((xv, yv), dim=2)
result

tensor([[[0, 0],
         [1, 0],
         [2, 0]],

        [[0, 1],
         [1, 1],
         [2, 1]],

        [[0, 2],
         [1, 2],
         [2, 2]]])

In [10]:
result.shape

torch.Size([3, 3, 2])

In [15]:
result = result.view((1, 1, 3, 3, 2))

In [16]:
result.shape

torch.Size([1, 1, 3, 3, 2])

In [17]:
result.float()

tensor([[[[[0., 0.],
           [1., 0.],
           [2., 0.]],

          [[0., 1.],
           [1., 1.],
           [2., 1.]],

          [[0., 2.],
           [1., 2.],
           [2., 2.]]]]])

In [10]:
import os
from pathlib import Path

image_path = "..\\rdd2020\\rddc_yolo\\images\\train\\Czech_000006.jpg"
sa, sb = os.sep + "images" + os.sep, os.sep + "labels" + os.sep

In [11]:
sa, sb

('\\images\\', '\\labels\\')

In [12]:
image_path.replace(sa, sb, 1)

'..\\rdd2020\\rddc_yolo\\labels\\train\\Czech_000006.jpg'

In [13]:
image_path.split('.')[-1]

'jpg'

In [14]:
image_path.rsplit(image_path.split('.')[-1], 1)

['..\\rdd2020\\rddc_yolo\\images\\train\\Czech_000006.', '']

In [15]:
image_path = 'txt'.join(image_path.replace(sa, sb, 1).rsplit(image_path.split('.')[-1], 1))

In [16]:
image_path

'..\\rdd2020\\rddc_yolo\\labels\\train\\Czech_000006.txt'

In [19]:
Path(image_path).parent.with_suffix(".cache")

WindowsPath('../rdd2020/rddc_yolo/labels/train.cache')

In [27]:
lb_file = '..\\rdd2020\\rddc_yolo\\labels\\train\\Czech_000006.txt'
with open(lb_file, "r") as f:
    lines = f.read()

In [28]:
lines

'0 0.25583333333333336 0.7308333333333333 0.041666666666666664 0.11166666666666666\n'

In [29]:
lines.strip()

'0 0.25583333333333336 0.7308333333333333 0.041666666666666664 0.11166666666666666'

In [30]:
lines.splitlines()

['0 0.25583333333333336 0.7308333333333333 0.041666666666666664 0.11166666666666666']

In [3]:
list1 = [1, 2 ,3 ,4 ,5 ,6 ,7 ,8 ,9, 0]
index1 = [4, 6, 8]
print(list1[0])

1


In [9]:
import torch

lobj = torch.tensor(0.68)
lcls = torch.tensor(0.36)
lbbox = torch.tensor(0.55)

In [10]:
loss_item = torch.cat((lobj, lcls, lbbox))

RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated

In [14]:
from models.MKMMD import MKMMD2
mk_mmd = MKMMD2()
batch_size = 8
total = torch.rand((2 * batch_size, 256, 80, 80), device="cuda", dtype=torch.float32)
loss = mk_mmd(total.flatten(1), batch_size).view(1)

In [7]:
torch.cat([loss_item, loss])

RuntimeError: zero-dimensional tensor (at position 1) cannot be concatenated